Added Json return, searchmodel & pagination
itthardik/LibraryApi pull request #2
Opened 2024-08-07 18:09 UTC by itthardik

**Member API Fix**
  1. Changed return type of Get Repo function such that they will return JsonResult
  2. Added SearchModel for Members
  3. Added Pagination in GetAllMembers

2024-08-08 04:02 UTC, ITT-SurabhiSa requested changes

2024-08-08 07:50 UTC, itthardik commented
Added new commit for SP

2024-08-08 07:50 UTC, itthardik commented on Utility/CustomUtility.cs
> +                if (member.Email != null)
Added new commit for SP

2024-08-12 02:35 UTC, ITT-SurabhiSa approved these changes

2024-08-12 02:35 UTC, merged